
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[[exemptions.backtrace-ext]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.console]]
version = "0.15.11"
criteria = "safe-to-run"

[[exemptions.crossbeam-deque]]
version = "0.8.6"
criteria = "safe-to-run"

[[exemptions.crossbeam-utils]]
version = "0.8.21"
criteria = "safe-to-run"

[[exemptions.deadpool-runtime]]
version = "0.1.4"
criteria = "safe-to-run"

[[exemptions.encode_unicode]]
version = "1.0.0"
criteria = "safe-to-run"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.globwalk]]
version = "0.9.1"
criteria = "safe-to-run"

[[exemptions.humansize]]
version = "2.1.3"
criteria = "safe-to-deploy"

[[exemptions.icu_collections]]
version = "2.1.1"
criteria = "safe-to-deploy"

[[exemptions.libm]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.miette]]
version = "7.6.0"
criteria = "safe-to-deploy"

[[exemptions.miette-derive]]
version = "7.6.0"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "8.0.0"
criteria = "safe-to-deploy"

[[exemptions.num-format]]
version = "0.4.4"
criteria = "safe-to-deploy"

[[exemptions.openssl]]
version = "0.10.75"
criteria = "safe-to-deploy"

[[exemptions.owo-colors]]
version = "4.2.3"
criteria = "safe-to-deploy"

[[exemptions.portable-atomic]]
version = "1.11.1"
criteria = "safe-to-deploy"

[[exemptions.portable-atomic-util]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.5.18"
criteria = "safe-to-deploy"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.stable_deref_trait]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.supports-color]]
version = "3.0.2"
criteria = "safe-to-deploy"

[[exemptions.supports-hyperlinks]]
version = "3.1.0"
criteria = "safe-to-deploy"

[[exemptions.supports-unicode]]
version = "3.0.0"
criteria = "safe-to-deploy"

[[exemptions.terminal_size]]
version = "0.1.17"
criteria = "safe-to-deploy"

[[exemptions.unarray]]
version = "0.1.4"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.105"
criteria = "safe-to-deploy"

[[exemptions.windows-strings]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.59.0"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.60.2"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.27"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.27"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.8.2"
criteria = "safe-to-deploy"
